### PR TITLE
Support page with simple redirects

### PR DESCRIPTION
**Pull request by jngbng**
Set cookie by executing the bundled javascript and reload the page.

### CODE REVIEW

**Comment by codemanki** [comment]
@jngbng looks great! Could you please add some UTs for this feature?

**Comment by jngbng** [comment]
@codemanki Added one UT for this feature.

**Comment by codemanki** [comment]
@jngbng looks great, but one last thing. 

You've changed the signature of the callback `cloudscraper.get(url, function(error, response, body) {` by adding a second argument that in general breaks library for existing users. Could you please change it to `function(error, body, response)` ? I'm working on 2.0 version of cloudscraper where i will introduce some breaking changes together  with this on. But right now i don't think this is a right moment. Thanks!

**Comment by jngbng** [comment]
@codemanki  I have reverted the problematic commit.

**Comment by codemanki** [comment]
@jngbng super cool. Merging this, adding minor fixes and releasing. Thanks so much for doing this feature :)

**Pull request merged**
