### PR TITLE
Switched brotli to optional dependency

### PR DESCRIPTION
**Pull request by lillem4n**
Since brotli is not required it should be an optional dependency, I think. :)

### CODE REVIEW

**Comment by pro-src** [comment]
@lillem4n Peer dependencies are optional dependencies. The difference is npm/yarn won't attempt to install peer dependencies for you. If this PR were to be accepted, the optional brotli dep. would needlessly be installed on e.g. Node.js v12.

**Comment by pro-src** [comment]
The PR is very much appreciated though!

**Comment by lillem4n** [comment]
Hm, I see. Maybe in practice peer dependencies are optional, but as I understand them they are ment to be a requirement. The npm WARN states it *must* be installed:

Screenshot from 2019-09-25 16-17-08

However, to have optional dependencies installed by default seems like a bad option as well. That would be more "right", though, I think.

I won't fight for this though, just really hate to have those WARN:s in my logs when they are not needed. :D

**Comment by pro-src** [comment]
The warning is helpful if you're unaware that your project might need brotli installed. Saving brotli as a dependency in your own project will remove the warning whereas making the suggested change here would install the dependency in *every* project.

This is how I've seen it done in practice and it makes sense.

**Comment by pro-src** [comment]
:thinking: We could opt to not specify brotli as a dependency. However, if we did that, we'd get more bug reports... The reason being not everybody will read the project's markdown and in some cases, not accepting brotli responses will result in a (403) captcha.

As a comprimise, we could instead emit a warning at runtime when encountering a captcha or 1020 access denied, etc.

@codemanki thoughts?

**Comment by codemanki** [comment]
1 warning vs potential bugs and questions? :) I choose a warning

**Comment by lillem4n** [comment]
I'm sold, thank you a lot for thinking about it and convince me. If I can manage npm to change the behavior so optional dependencies do not get installed by default, we can revisit this. ;)

**Pull request closed without merging**
