### PR TITLE
Backport TLSv1.3 secure ciphers

### LINKED ISSUE #211: CaptchaError: captcha v4.0.1 (SSL negotiation)
```
var uri = "https://nanime.in";
  var cloudscraper = require("cloudscraper").defaults({
    headers: {
      Connection: "keep-alive",
      "User-Agent":
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
      Accept:       "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "Accept-Language": "en-US,en;q=0.9"
    }
  });

  cloudscraper.get(uri, function(error, response, body) {
    if (error) {
      throw error;
      res.send(error);
      next();
    } else {
      console.log(body);

      res.send(body);
      next();
    }
  });
```
```

/media/karnadi/Boice/Proyek/scraper-api/node_modules/request-promise-core/lib/plumbing.js:130
            throw thrownException;
            ^
CaptchaError: captcha

```

### PR DESCRIPTION
**Pull request by pro-src**
Fixes #211

### CODE REVIEW

**Comment by pro-src** [comment]
I've ran some feature tests on 155 different versions of node: https://github.com/pro-src/node-ciphers-ci-test

Due to the complicated nature of this problem, I can't say for certain that this is a guaranteed fix but it should at least mitigate some of the problems that user's have been experiencing. Also, I'm thinking that Cloudflare is likely to update their SSL related checks so we'll need to keep an eye on this.

**Comment by codemanki** [comment]
Merging and releasing
1_snTXFElFuQLSFDnvZKJ6IA

**Comment by codemanki** [comment]
@pro-src it is ready to be merged, right?

**Comment by pro-src** [comment]
Yeah, it is ready to be merged. TLSv1.3 is TLS done right. We're only backporting a few very secure openssl options to avoid triggering a CAPTCHA. At worst, it does nothing since openssl will simply ignore any unsupported ciphers. At best, it completely solves the problem by changing the defaults to more closely match the defaults of current openssl versions.

Node will call this openssl function to set the ciphers: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_cipher_list.html 

> The control string str should be universally usable and not depend on details of the library configuration (ciphers compiled in). Thus no syntax checking takes place. Items that are not recognized, because the corresponding ciphers are not compiled in or because they are mistyped, are simply ignored. Failure is only flagged if no ciphers could be collected at all.

Simply put, we're using a cipher list control string that includes the already existing defaults, plus a few additions if the openssl version is outdated.

I tested a 155 versions of node between v6 and the latest v12. I found that there is generally only 4 unique default cipher suite lists. Every version of the list is a subset of the most recent list and several cipher suites are present in all 4 lists. Thus, we can conclude that is not the inclusion of the default ciphers that are causing the problem. It is the absence of expected ciphers and/or other attributes of the SSL negotiation. The chief difference in the lists being that some of the TLSv1.3 options present in recent versions of node are not present in versions of node that were compiled with `openssl <= 1.1.1`.

It still remains to be seen if this completely solves the problem since there are other variables in the TLS `clientHello` that could potentially cause our requests to uniquely identified. Particularly, the signature algorithms extension: https://timtaubert.de/blog/2016/07/the-evolution-of-signatures-in-tls/

**Comment by codemanki** [comment]
Released as `4.1.0`. Thank you @pro-src  :)

**Pull request merged**
