### PR TITLE
Fix for the case when using proxies

### PR DESCRIPTION
**Pull request by DrakkLord**
Hello,

I've used this module for bypassing the cloudflare protection which worked, however when I used it with proxy servers I got problems.

If you make a request with a proxy

> response.request.host

that will be the same as the proxy server's address instead of the target site's address so the solution is to parse

> response.request.href

and use the host part of it which will correctly contain the host name for both proxy and non-proxy usage.

### CODE REVIEW

**Comment by codemanki** [comment]
@DrakkLord thanks for doing this. Could you please add some UTs?

**Comment by DrakkLord** [comment]
@codemanki Excuse me but what is an "UT"?

**Comment by codemanki** [comment]
@DrakkLord sorry, unit tests or specs. You can find them here https://github.com/codemanki/cloudscraper/tree/master/specs/tests 
It would be great if you could add some tests that cover your change

**Comment by pro-src** [comment]
lol

**Comment by pro-src** [comment]
@codemanki I think this is security bug because `request/request` will no longer treat the proxy as a proxy but as the request target thus potentially bypassing security checks that requests are meant to undergo. If an authorization header was added to the initial call to cloudscraper and the response is a 302 with a different domain in the location header, `request/request` will remove the authorization header before the redirect occurs. However, if cloudscraper makes a second request with the proxy as the target... See where that is going?

I'll write the tests for this in a new PR.

**Comment by codemanki** [comment]
Implemented in https://github.com/codemanki/cloudscraper/pull/106

**Pull request closed without merging**
