### PR TITLE
Fix bug with setTimeout match length

### PR DESCRIPTION
**Pull request by pro-src**
My fault :sweat_smile:

### CODE REVIEW

**Comment by codemanki** [comment]
I wonder why tests were green 🤔

**Comment by pro-src** [comment]
Because we set the timeout explicitly in tests and I'm an idiot right now. :roll_eyes:

**Comment by codemanki** [comment]
No you are not :/

**Comment by pro-src** [comment]
Well, the fix in this PR needs to be fixed....lol
Which isn't an immediate problem unless Cloudflare updates before we fix it.
The length of the match when timeout parsing succeeds is 3.
It should be: ```if (match.length > 2) ....``` not ```if (match.length > 1) ...```

**Comment by pro-src** [comment]
This is the correct fix: https://github.com/pro-src/cloudscraper/commit/72ceaf415b5343196e4cbdc135f48ab0d4875208

**Comment by codemanki** [comment]
So it should be rather `if (match.length > 2) {`? I will then release it as 3.9.1

**Comment by codemanki** [comment]
Or not? @pro-src  :)

**Comment by pro-src** [comment]
Yes, please

**Comment by codemanki** [comment]
Done! Thanks!

**Comment by pro-src** [comment]
Thx for fixing my screw up so fast. I'm not sure what to do about the tests. Reducing the timeout was the only way to make things work with mocha.

**Pull request merged**
