### PR TITLE
Add promise support for get, post, and request

### PR DESCRIPTION
**Pull request by pixelart7**
Today, I reviewed @serge1peshcoff's #30 that add promise support to the existed functions, but his modified code does not work well with the callback methods because of the change in arguments ordering.

Hence, I forked this repo and modified some codes in get, post, and request functions to accept a promise call. The approach is different to @serge1peshcoff as I modified only the entry functions, and I left the private function almost untouched. I also added tests for the promise calling.

With these modification, there are some changes:

1. `.get(url, headers)`, `.post(url, body, headers)` should return a promise unless the last argument is replaced by a function.
2. `.get(url)`, `.post(url, body)` should return a promise.
3. `.request(options)` should return a promise.
4. `.get(url, callback)`, `.post(url, body, callback)`, `.request(options, callback)` should work correctly.
5. The resolved promise should return an object with keys: `response `and `body`, which is different from callback function.
6. The rejected promise should be catchable.

Thank you.

### CODE REVIEW

**Comment by codemanki** [comment]
Hey! Thanks for this, great job! I will review it and merge asap

**Comment by bretthex** [comment]
@codemanki Bump!

**Comment by mxs** [comment]
bump! 👍

**Comment by pro-src** [comment]
`request-promise` should be used for this. See https://github.com/codemanki/cloudscraper/issues/68

**Comment by codemanki** [comment]
Implemented in https://github.com/codemanki/cloudscraper/pull/106

**Pull request closed without merging**
