### PR TITLE
Cloudflare form update

### PR DESCRIPTION
**Pull request by elpaxel**
Cloudflare changed method of the form, url and one input.

### CODE REVIEW

**Comment by elpaxel** [comment]
#286 #285

**Comment by puleeno** [comment]
- [x] It's working for me. Thanks @elpaxel

**Comment by Bassintag** [comment]
Working fine for me too thanks @elpaxel, hope this will be merged soon

**Comment by codemanki** [comment]
@elpaxel thanks for the fix! I have created this new [PR](https://github.com/codemanki/cloudscraper/pull/288) with additional improvements and tests. Closing your PR for now.

**Pull request closed without merging**
