### PR TITLE
Randomize UA

### PR DESCRIPTION
**Pull request by codemanki**
Fixes https://github.com/codemanki/cloudscraper/issues/77

@pro-src i first created a `randomizeUserAgent` flag on defaultParams, but then decided to just randomize the UA by default, as that flag was brining more confusion than actual value

### CODE REVIEW

**Comment by pro-src** [comment]
@codemanki I think that if this is going to be on by default then there should be at least a minor version bump. There also needs to be a warning in the README to inform people that sending a cookie that was acquired with a different user agent is a bad idea. The user agent should always be stored with the session cookie. This could very well be a breaking change if anybody is already using v3 and is storing session cookies for reuse.

**Comment by codemanki** [comment]
@pro-src so you are saying that it should be actually a flag that is off by default?

**Comment by pro-src** [comment]
@codemanki, what about adding a method to apply a random user agent?
```js
// Somewhere in the custom defaults function
cloudscraper.setUserAgent = setUserAgent;

// Pseudo definition
function setUserAgent(ua) {
  if (ua === 0) {
    ua = this.defaultParam.headers['User-Agent'];
    var old = ua;
    while (ua === old) ua = randomUA();
  }

  if (!ua || typeof ua !== 'string') {
    throw new TypeError('Expected userAgent to be a non-empty string, got ' +
      typeof (ua) + ' instead.';
  }

  this.defaultParam.headers['User-Agent'] = ua;
}

// Usage
var cloudscraper = require('cloudscraper');
cloudscraper.setUserAgent(0);
```

**Comment by pro-src** [comment]
@codemanki, I'm curious as to how unique those user agents are. We won't them to be as common/popular as possible. Can you switch out your browser's UA and check them with the EFF's https://panopticlick.eff.org/

**Comment by pro-src** [comment]
@codemanki 
> so you are saying that it should be actually a flag that is off by default?
I'm saying it should be off by default but it doesn't necessarily have to be a flag.

**Comment by codemanki** [comment]
>I'm saying it should be off by default but it doesn't necessarily have to be a flag.
Then I would just leave it as it is and add a notice to the readme, saying that UA randomization is a nice to have but should be handled manually by user. 
If user wants to use UA headers in more advanced way, they would want to use something like https://www.npmjs.com/package/random-ua 
The suggested by you random UA filling looks like a workaround, that is not very obvious and is limited to the defined list of 10-15 UAs.

**Comment by pro-src** [comment]
@codemanki Actually, I'd rather have this on by default and release it now in the patch version then to not have it all, lol. No convenience methods necessary. However we could just document the method as only randomly returning one of the ~5 most popular user agents. Because they won't be aware of the method unless they read the readme anyway...

**Comment by codemanki** [comment]
@pro-src but if it is on by default, then users should also keep a track of selected UA. But on other hand, if cloudscraper is used in non-advanced way, users won't probably save cookies to reuse them and etc.

So should it be a method as you suggested, or a flag? :)

**Comment by pro-src** [comment]
@codemanki I think a method would better so we can change the user agent on the demand. If getting a captcha, you might be able to circumvent it just by changing the UA. See this issue: https://github.com/Anorov/cloudflare-scrape/issues/190

So, we only really need either a flag or method but if you wanted to you could add both. I'm neutral on it.

**Comment by pro-src** [comment]
According to the EFF's panopticlick:
* one in 220600.0 browsers have this value: `Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36`
* one in 220609.0 browsers have this value: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.21 (KHTML, like Gecko) konqueror/4.14.10 Safari/537.21`
* one in 220617.0 browsers have this value: `Mozilla/5.0 (iPad; CPU OS 5_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko ) Version/5.1 Mobile/9B176 Safari/7534.48.3`
* one in 220628.0 browsers have this value: `Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10`

I was just checking them in order of appearance. I didn't check all of them. The user agent's found at http://www.browser-info.net/useragents (Most Popular User Agents section) appear to be way more common.

For example:
* one in 9193.79 browsers have this value: `Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.6.01001)`

**Comment by pro-src** [comment]
:thinking: Hmm, something does seem right about IE6 being that popular.

**Comment by pro-src** [comment]
@codemanki Did you decide on what to do with this?

**Comment by codemanki** [comment]
@pro-src oh snap. yes, i want to continue with a flag, as it looks like we are currently using this kind of strategy for configuration. 👍  ?

**Comment by pro-src** [comment]
@codemanki :thinking: If a flag is introduced, the UA would have to be set during the first `performRequest`?

**Comment by pro-src** [comment]
@codemanki :thinking: If a flag is introduced, the UA would have to be set during the first `performRequest` and kept for all future calls to `cloudscraper`? Or would it be the case that you could only enable/disable this by using the `defaults` function?

**Comment by pro-src** [comment]
@codemanki See my https://github.com/codemanki/cloudscraper/issues/62#issuecomment-472130328 about adding a flag that should apply to all requests.

**Comment by pro-src** [comment]
I'm just noting this here since changing the UA can potentially bypass a captcha.
```js
var cloudscraper = require('cloudscraper');
var errors = require('cloudscraper/errors');

cloudscraper.get('http://example-site.dev')
  .catch(function(error) {
    if (error instanceof errors.CaptchaError) {
      cloudscraper.defaultParams.headers['User-Agent'] = 'new UA';
      return cloudscraper.get('http://example-site.dev');
    }
  })
  .then(doSomethingWithBody)

**Comment by codemanki** [comment]
@pro-src hey. sorry, i was out for some time, now i'm back. I will take a look at your comments and will adjust my PR

**Comment by pro-src** [comment]
@codemanki Thanks for the update!

**Comment by codemanki** [comment]
To reopen this PR. Do we want to set a new UA on errors? Or on each request?

**Comment by pro-src** [comment]
> Do we want to set a new UA on errors?

I like the idea of having an option that causes the UA to be changed if we get a captcha. However, you can already do that using the current API.

> Or on each request?

Changing the UA on a per-request basis is definitely a bad idea.

I really don't want to delay this PR any further, can we just merge it as is?

I do have a couple concerns:
* This is changing the default behavior which is not an issue if users have to explicitly enable it.
* The user should reuse the user-agent if cookies are reused in later sessions which complicates things.

The first concern could normally be resolved by a major version bump but users have to update to the latest version otherwise cloudscraper won't work for the latest challenge. Once the parsing methods are separated from the main library, we should consider backporting so breaking changes aren't forced on users.

The second concern would be addressed by updating the README but maybe later we could add a method to get the cookies and UA together?

**Comment by pro-src** [comment]
@codemanki I just realized that we haven't updated the project markdown to mention saving the UA with the cookies. Probably should do that...

**Pull request merged**
