### PR TITLE
Add typescript definitions and tests

### LINKED ISSUE #265: Create typescript definition file
Pretty please :)

### PR DESCRIPTION
**Pull request by pro-src**
Closes #265

### CODE REVIEW

**Comment by pro-src** [comment]
I think travis-ci failed to honor the `on_success` setting:
https://github.com/codemanki/cloudscraper/blob/db4af38f2d653066faf06e507a57cbb7b332bc32/.travis.yml#L23-L25

Docs haven't changed: https://docs.travis-ci.com/user/notifications/#configuring-webhook-notifications

I'm guessing they're more than aware of the issue, if the same occurred with hundreds of builds recently: https://www.traviscistatus.com

**Comment by pro-src** [comment]
@lillem4n

**Comment by lillem4n** [comment]
This is golden, thank you so much!

**Comment by etnann** [comment]
Could you write an example of how to import and use the library using typescript?
I tried with 

```js
import * as cloudscraper from "cloudscraper";
let html_doc = await cloudscraper(options);
```

but Visual Studio code shows me an error: *This expression is not callable. Type 'CloudscraperAPI' has no call signatures*

**Comment by lillem4n** [comment]
`import cloudscraper from 'cloudscraper';` should be enough. We're using it like this with TS 3.7.2.

**Pull request merged**
