### PR TITLE
Promise Support

### LINKED ISSUE #92: Allow the request module to be replaced
As mentioned in #58

### PR DESCRIPTION
**Pull request by pro-src**
***Don't merge.*** I'll need to rebase this once #91 is merged as it's based on it.
This could use some `request-promise` specific tests. Other than that, it's good. I don't think code coverage was decreased.

It adds request-promise as a dependency and makes adjustments where necessary. It is completely backwards compatible with the v3.0.0 branch and all tests are passing for me. I had forgot that request was a peer dependency of request-promise and the CI build failed...lol, It's fixed now.

Closes #92 
And the following PRs
Closes #43 
Closes #30

### CODE REVIEW

**Comment by pro-src** [comment]
@codemanki, we don't have to allow the request module to be a passable option for this PR. Let me know and I'll remove it.

**Comment by codemanki** [comment]
@pro-src i want to take a closer look at this PR if you don't mind

**Comment by codemanki** [comment]
@pro-src i think i will just merge it so i won't block your work

**Comment by pro-src** [comment]
So a rebase wasn't necessary. Thats nice. If you need more time to review, it's cool with me. Better safe than sorry.

**Comment by pro-src** [comment]
@codemanki, I've since discovered some issues with the promises that should be addressed. If the `resolveWithFullResponse` option is used, it's possible `response.body` will always be a buffer. By default the promise will resolve with the body and not the full response so I missed it. An easy fix for that is just to replace `response.body` if `realEncoding` is defined. The other problem is that it's really hard to write good tests for the promise support. I'm working on something but race conditions are currently blocking my progress.

**Pull request merged**
