### PR TITLE
Adjusting code to parse & submit new captcha

### PR DESCRIPTION
**Pull request by drdokk**
#291 #286

### CODE REVIEW

**Comment by drdokk** [comment]
Now I guess CI is failing because of tests (I din't provide test update for this)

**Comment by Bassintag** [comment]
Please merge this, it fixed the issues with the captcha challenge

**Comment by codemanki** [comment]
@Bassintag I will, but I need to fix the tests first. Hopefully will do it today

**Comment by Bassintag** [comment]
> @Bassintag I will, but I need to fix the tests first. Hopefully will do it today

Great thank you very much, this is pretty critical for our application

**Comment by codemanki** [comment]
@Bassintag you could then help me out and look into fixing the specs ;) Just saying

**Comment by Bassintag** [comment]
@codemanki true, not much free time right now but in the future I will definitely try to get involved, but I got to get familiar with the codebase first

**Comment by codemanki** [comment]
@Bassintag no problem. Thanks, hope to see some contributions from you in future

**Comment by codemanki** [comment]
Thank you @drdokk !

**Pull request closed without merging**
